version: '3'

services:
  django:
    image: colemk/webserver:1.0
    volumes:
      - ./web/kaleidoscope:/kaleidoscope
    build: ./web/kaleidoscope
    #command: python manage.py runserver
    ports:
      - "80:80"
  # machinelearning:
  #   image: ml
  #   volumes:
  #     - ./web/kaleidoscope:/web/kaleidoscope
  #   build: ./ML

#run with 
#docker compose up --build